### ISSUE TITLE
Help using  trackingallowedpids.ino

### ISSUE THREAD

**Issue by acca84** [timurrrr/arduino-RaceChrono#3]
Hello, i'm trying using this sketch on ESP32S3
It compiles and uploads to baord, i can connect to racechrono under android, but i have the following message : 
"  No PIDs are allowed."
I'd like to retreive gps and lap infos (no need of canbus)
Could someone explain how to do it please ?
Thanks

**Comment by timurrrr** [comment]
The device only does what RaceChrono tells it to do.
You need to set up a "vehicle profile" in RaceChrono and add custom data channels with their PIDs.
